apiVersion: v1
kind: Service
metadata:
  name: pingpong-svc
spec:
  type: NodePort
  selector:
    app: pingpong
  ports:
    - protocol: TCP
      port: 80
      nodePort: 31000
      targetPort: 3000
